### ISSUE TITLE
Warning! Error encountered during contract execution [Bad instruction]

### ISSUE THREAD

**Issue by MeowMix9** [poanetwork/token-wizard#1079]
If you are reporting a problem with Token Wizard, please include the following information:

I used the Mainnet, and a portion of the contract has failed. Also, what do I open this zip file with? Should I try opening in Notepad and pasting in Remix?

*Your answer*

### If you were able to create it, what is the URL of your crowdsale?

I was unable to move forward after paying network fees/gas.

### Do you have screenshots showing the problem?

No, unfortunately.

### Do you see errors in the dev console? If yes, please include a screenshot

No.

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by MeowMix9** [comment]
This is the failed contract address: 0x0f09c8b81589ce748534b9f404bae066bebc2ca5 

Anyone know how I fix this? OR if it is even something that can be fixed?

**Comment by vbaranov** [comment]
@MeowMix9 

zip file contains source codes of your crowdsale smart-contracts and its metadata. You'll use it for verification of your smart-contracts in Etherscan. The verification guide is [here](https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Verifying-Contracts).

We need parameters of your crowdsale and clarification of your deployment process. Because from what I see from Etherscan, that the deployment process of your crowdsale is not finished yet (not all transactions were signed).

**Comment by vbaranov** [comment]
@MeowMix9 Smart-contracts' verification is the manual process. I will close this issue. Please reopen it or open a new one if you will have problems with a new deployment.
