### ISSUE TITLE
Json parsing of .abi files fails with SyntaxError "Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by pratimasethi** [poanetwork/token-wizard#1134]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

"localhost:8545"
### If you were able to create it, what is the URL of your crowdsale?

*Your answer*

### Do you have screenshots showing the problem?

yes

### Do you see errors in the dev console? If yes, please include a screenshot

![image](https://user-images.githubusercontent.com/3583447/45357673-9e6e4d80-b5e4-11e8-828d-7aa5c5e6fc96.png)

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.
[tokenwizard.log.zip](https://github.com/poanetwork/token-wizard/files/2370768/tokenwizard.log.zip)

---

**Comment by vbaranov** [comment]
@pratimasethi the issue was in submodule `solidity-flattener`. It was fixed in this PR https://github.com/poanetwork/solidity-flattener/pull/28/files. Please update submodules with `git submodule update --init --recursive --remote` and start wizard again. Please confirm, that the issue was fixed for you.

**Comment by vbaranov** [comment]
Closed due to https://gitter.im/poanetwork/ico-wizard?at=5b98c009e481f854a6a761fc
