### ISSUE TITLE
(Feature) Implement local storage for mobx state

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/token-wizard#529]
Problem:
when a user refreshes a page he loses the state of the crowdsale and not able to download the source code. Implementation of the feature allows users to continue set up of a crowdsale in the same browser after refresh

Solution:
store mobx state in local storage state after each interaction

---

Pending:

- [x] Persist stores in local storage
- [x] Clear storage properly after the deploy is finished
- [x] Save `deploymentStep` after each step (not just when a transaction fails)
- [x] Notify that there is an incomplete deploy if user opens the home page of the wizard
- [x] Don't show the progress modal if user refreshes the page after all steps are done
- [ ] Show skip button if transaction fails

**Comment by fvictorio** [comment]
We discussed a little about this with @fernandomg and while persisting the mobx state in local storage is a part of the solution, there are several things that need to be taken into account (when is the storage cleaned, what happens if the user's browser crashes and they open the wizard from the beginning, how the persistence interacts with non-serializable objects like web3).

While we work on all that stuff, a simple thing we can implement is an alert when the user refreshes or closes the tab in the middle of the deployment, to reduce the chances of someone accidentally losing ether.

@igorbarinov I'll create an issue for that if you think it's a good idea.
