### ISSUE TITLE
(Fix) Manage page: the rate and supply inputs are not disabled, if crowdsale is started

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/token-wizard#542]
https://github.com/poanetwork/ico-wizard/pull/537#issuecomment-362088690

>The rate and supply inputs are not disabled, but if you modify them the transaction fails.

**Comment by hashguide** [comment]
I know before we were able to change the rate and supply of the crowdsale after it has started as well, just the start time was unable to. Has this change due to the security audits or is this the intended way? 

Allowing to change the rate while crowdsale is running allows you to use single tier crowdsale to have a multi-tier bonus system of some sort without having to deploy the same amount of tiers as rate changes.

**Comment by vbaranov** [comment]
Yes, it was one of the points indicated in security audit. We closed this possibility due to it. For now, owner should create multiple tiers to implement flexible bonus system.

**Comment by hashguide** [comment]
Ok sounds good. Just wanted to be clear about it as well.
