### ISSUE TITLE
(Bug) Blank page after switching networks when crowdsale setup is already started

### ISSUE THREAD

**Issue by pablofullana** [poanetwork/token-wizard#593]
Looks like we are missing a redirect to the first step (or any other workaround with a proper message to avoid user confusion) when user switches networks after the crowdsale setup was started.

### Steps to reproduce:

1. Picked Main network in metamask
1. Proceed to 'Crowdsale Contract' step and picked the only available option.
1. Proceed to 'Token Setup' step and filled in all the inputs with valid values.
1. Proceed to 'Crowdsale Contract' step
1. Switched to Kovan network in metamask.
1. Got a blank page with the following error in the browser console:
```Uncaught TypeError: Cannot read property 'addr' of undefined```

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Mainnet first, Kovan then. But my guess is that this is not relevant at all.

### Do you see errors in the dev console? If yes, please include a screenshot

[wizard.poa.network-1518626368475.log](https://github.com/poanetwork/token-wizard/files/1724852/wizard.poa.network-1518626368475.log)

---

**Comment by fvictorio** [comment]
I already mentioned this somewhere, but I think it would be a good idea to use something like this: https://github.com/coopermaruyama/react-web3

It would help with several things: centralizing the "No metamask" messages, being able to assume that web3 is present, and reacting to account/network changes (that library does not offer a callback for network changes, but I don't think it would be hard to add).

**Comment by pablofullana** [comment]
Possibly related to: #647

**Comment by fvictorio** [comment]
This seems to be a "feature" of MetaMask, see https://github.com/MetaMask/metamask-extension/pull/179

So I think the underlying issue is how we handle refreshes, particularly refreshing in step four before the deploy begins: since the deploy didn't start, the crowdsale data is not fetched from local storage.

Please note that this is mainly an issue in the dev environment: in production, the deploy starts right away, so you don't have the opportunity to refresh before it starts.

I'm going to fix it anyway, because it's annoying and because maybe some day we show the `Start deploy` button in production and this bug will be waiting there.
