### ISSUE TITLE
(Feature) Bulk import on whitelist addresses

### ISSUE THREAD

**Issue by spatade123** [poanetwork/token-wizard#600]
Hi, 

I tried using POA Network for crowdsale demo test and really liked it. I will like to know how i can add bulk white-list addresses when creating a new contract? or if the feature doesn't exists any timeline when this feature will be availble?

Thanks,
Sagar

**Comment by TRIHRD** [comment]
Author would like to move into this feature with a little help from GitHub ..The reason this ICO should be successful is  because , Countries are trying to make it so different nationalities cannot own real estate. But if you own coins,you will have a share in real estate When some 20% convert to FIAT. and list on the ASX buying secure long term commercial,industrials Fully leased own the buildings through crowdfunding. Also we will be developers of empty land if opportunity arises in pacific, Develop for domestic sections and managed rentals. Accounts will be audited as per ASX.

**Comment by pablofullana** [comment]
Hi @spatade123

> I tried using POA Network for crowdsale demo test really liked it

Glad to hear that!

>There is no feature nowadays for doing what you describe. Nevertheless, we had this idea in our backlog. It's good to see that it was actually brought up by someone else, this helps us with prioritization.

There are couple of alternatives we were analyzing and we'd appreciate your feedback here:

1. To have an 'upload text/csv' button via which the user will provide the page with a set of [address,min,max] rows. Inputs will be automatically generated and filled-in based on this file contents.
1. To be able to paste a list of addresses, with the same format as the previous point, and have the inputs filled-in with that data.

Both alternatives will also allow the user to overwrite the automatically generated and filled-in inputs, add more or even remove them as required.

Any preferences from your perspective as a user?

**Comment by spatade123** [comment]
Hi pablofullana,

I like the first option 1) To have an 'upload text/csv' button via which the user will provide the page with a set of [address,min,max] rows. Inputs will be automatically generated and filled-in based on this file contents.

In case this request gets prioritization any timeline for this feature to be in production?

Thnaks,
Sagar

**Comment by pablofullana** [comment]
hey @spatade123 thanks fr your feedback. There's no timeline for this feature right now, we'll have to prioritize this one within the rest features in our pipeline. We'll do our best to have it in production quite soon.
