### ISSUE TITLE
(Bug) persist-crowdsale-state-#529: transaction is  generated if user refresh the page 

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#602]
### Issue related new feature, 
test page: https://5a87189fefbe5d658ef89ee4--ico-wizard.netlify.com/

### Steps to reproduce:
1. Start deployment
2. Refresh page and choose "Reload" in popup window
3. Refresh page again
Expected result: popup "reload" should appear and prevent from reload page
Actual result : user can reload page without notice, instead new transaction generated each time

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Rinkeby*

### If you were able to create it, what is the URL of your crowdsale?

*n/a*

### Do you have screenshots showing the problem?

https://drive.google.com/open?id=1gVIBvbBuI46_mxRecL14nuEn8C_NIYka

https://drive.google.com/open?id=1ika7y6rgcmY-nSUtNFLnPZ4q6E2fxAiU
### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

[5a87189fefbe5d658ef89ee4--ico-wizard.netlify.com-1518812643275.log](https://github.com/poanetwork/token-wizard/files/1732721/5a87189fefbe5d658ef89ee4--ico-wizard.netlify.com-1518812643275.log)

---

**Comment by fvictorio** [comment]
@dennis00010011b I think this is a browser thing. Take a look at this:

https://gist.github.com/7cf9038ba91831ad71bb4ae1905c9ab7

That page should always show the alert. But if you click the refresh button twice, the second time it won't show the alert. If you click the refresh button, then click the input, and then the refresh button again, it will work. My guess is that the alert doesn't show up if you don't interact with the page somehow. This doesn't happen if you press F5 instead of clicking the refresh button, maybe because pressing that key counts as an interaction.

**Comment by fvictorio** [comment]
Closing this. Please re-open it if you think there's something we can do about it.
