### ISSUE TITLE
(Feature) Set tier to start automatically once previous one is over

### ISSUE THREAD

**Issue by pablofullana** [poanetwork/token-wizard#624]
As a User, when setting up my new crowdsale tiers, I'd like to be able to set a given tier to start automatically once previous one is over.

This will make easier the synchronization (when needed) and avoid changing multiple inputs in case I want to change other tiers end time.

**Comment by vbaranov** [comment]
Possible solution: it could be implemented at deployment stage with validating of *previous tier end date* and *next tier start date*. They should match each other. We could check it on pressing "Continue". And if any mismatching, Wizard could show a warning, where a user can continue, if it was intentional, or cancel and fix mismatching.

**Comment by vbaranov** [comment]
This will be implemented in Token Wizard 2.0
