### ISSUE TITLE
(Bug) Crowdsale is not modifiable after start

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#905]
Test URL : localhost with latest commit https://github.com/poanetwork/token-wizard/commit/5226634f72c9f83b9e13aff6b82ba8b336697c96
Steps:
1. Create modifiable crowdsale with whitelist
2. Wait until crowdsale starts
3. Open manage page as an owner and try to modify end time or add whitelist

Expected result:
 - owner should be able to modify duration and add whitelist
Actual result:
 - data are not modifiable

Exec ID : 0xe0f5f6b9079b146a6526979681193f46a1a15a85e4871925c79c4aceabdc630f
### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Ropsten*

### If you were able to create it, what is the URL of your crowdsale?

*http://localhost:3000/invest?exec-id=0xe0f5f6b9079b146a6526979681193f46a1a15a85e4871925c79c4aceabdc630f&networkID=3*

### Do you have screenshots showing the problem?
<img width="1440" alt="screen shot 2018-05-23 at 13 10 40" src="https://user-images.githubusercontent.com/14067096/40449251-c746c854-5e8c-11e8-9083-80474469a805.png">

### Do you see errors in the dev console? If yes, please include a screenshot

*No*

---

**Comment by vbaranov** [comment]
@dennis00010011b due to security reasons modification of duration for ongoing tier parameters is prohibited at Auth_os application layer. But if a tier is modifiable whitelist can be changed before start and for an ongoing tier too. Do you still have a problem with updating of tier for ongoing modifiable tier? Could you create a new live example (example from the issue is already ended)?

**Comment by dennis00010011b** [comment]
Not reproducible
