### ISSUE TITLE
(Bug)Minted- Manage page: The end time of 2nd tier changes synchronous with end time of 1st tier 

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#913]
Test URL : localhost with latest commit of branch 2.0 : https://github.com/poanetwork/token-wizard/commit/962130704e30e1a8b49bd97bc385f8f231b5639f

Steps:
1. Create crowdsale with 2 tiers
2. Open manage page as an owner
3. Change end time of 1st tier, look to end time of 2nd tier

Expected result:
 - end time of 2nd tier should not be changed 

Actual result:
 - end times 1st  and 2nd tiers  are changing together

Exec ID : 0xf504132553832d24fee6538f750a8e316563078571c5d179965576d51d353847

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Ropsten*

### If you were able to create it, what is the URL of your crowdsale?

*http://localhost:3000/invest?exec-id=0xf504132553832d24fee6538f750a8e316563078571c5d179965576d51d353847&networkID=3*
### Do you have screenshots showing the problem?

*https://drive.google.com/open?id=1YfPFleRTHhvJTGoveaz3JJVODN-S1zND*

### Do you see errors in the dev console? If yes, please include a screenshot

*No*

---

**Comment by vbaranov** [comment]
@dennis00010011b this is the feature. Related to this comment https://github.com/poanetwork/token-wizard/pull/898#issue-189669207. It is because actually, we change the duration in a tier (https://github.com/auth-os/applications/blob/master/TokenWizard/crowdsale/MintedCappedCrowdsale/contracts/crowdsale/CrowdsaleConsole.sol#L451) preserving duration of other tiers.

**Comment by dennis00010011b** [comment]
Not issue. Works as expected
